-- MySQL Script generated by MySQL Workbench
-- Wed Mar 16 20:55:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sistemadeclasse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sistemadeclasse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sistemadeclasse` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `db_sistemadeclasse` ;

-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_escola` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_disciplina` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_classe` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Periodo` SET('Manha', 'Tarde', 'Noite') NOT NULL,
  `Disciplina_id` INT ZEROFILL UNSIGNED NOT NULL,
  `Escola_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Classe_Escola1_idx` (`Escola_id` ASC) VISIBLE,
  INDEX `fk_Classe_Categoria1_idx` (`Disciplina_id` ASC) VISIBLE,
  CONSTRAINT `fk_Classe_Escola1`
    FOREIGN KEY (`Escola_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_escola` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classe_Categoria1`
    FOREIGN KEY (`Disciplina_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_nota` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `Qtde_atividade` SMALLINT(20) NOT NULL,
  `Nome_atividade` VARCHAR(45) NOT NULL,
  `Nota` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_frequencia` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `Presenca` INT ZEROFILL NOT NULL,
  `Falta` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_aluno` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `RA` TINYINT(11) ZEROFILL NOT NULL,
  `Nota_id` INT ZEROFILL UNSIGNED NOT NULL,
  `Frequencia_id` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Aluno_Nota_idx` (`Nota_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Frequencia1_idx` (`Frequencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Nota`
    FOREIGN KEY (`Nota_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_nota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Frequencia1`
    FOREIGN KEY (`Frequencia_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_frequencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_professor` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_classe_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_classe_aluno` (
  `Classe_id` INT UNSIGNED ZEROFILL NOT NULL,
  `Aluno_id` INT ZEROFILL NOT NULL,
  `qtdade_aulas` INT NOT NULL,
  PRIMARY KEY (`Classe_id`, `Aluno_id`),
  INDEX `fk_Classe_has_Aluno_Aluno1_idx` (`Aluno_id` ASC) VISIBLE,
  INDEX `fk_Classe_has_Aluno_Classe1_idx` (`Classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Classe_has_Aluno_Classe1`
    FOREIGN KEY (`Classe_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classe_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_professor_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_professor_classe` (
  `Professor_id` INT ZEROFILL NOT NULL,
  `Classe_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`Professor_id`, `Classe_id`),
  INDEX `fk_Professor_has_Classe_Classe1_idx` (`Classe_id` ASC) VISIBLE,
  INDEX `fk_Professor_has_Classe_Professor1_idx` (`Professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Classe_Professor1`
    FOREIGN KEY (`Professor_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Classe_Classe1`
    FOREIGN KEY (`Classe_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
