-- MySQL Script generated by MySQL Workbench
-- Mon May 16 16:13:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sistemadeclasse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sistemadeclasse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sistemadeclasse` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `db_sistemadeclasse` ;

-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_escola` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_disciplina` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_professor` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_classe` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `periodo` SET('Manha', 'Tarde', 'Noite') NOT NULL,
  `tbl_professor_id` INT ZEROFILL UNSIGNED NOT NULL,
  `tbl_disciplina_id` INT ZEROFILL UNSIGNED NOT NULL,
  `tbl_escola_id` INT UNSIGNED ZEROFILL NOT NULL,
  `tbl_classecol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Classe_tem_Escola_id` (`tbl_escola_id` ASC) VISIBLE,
  INDEX `fk_Classe_tem_Categoria_id` (`tbl_disciplina_id` ASC) VISIBLE,
  INDEX `fk_Classe_tem_Professor_id` (`tbl_professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Classe_Escola1`
    FOREIGN KEY (`tbl_escola_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_escola` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classe_Categoria1`
    FOREIGN KEY (`tbl_disciplina_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_classe_tbl_professor1`
    FOREIGN KEY (`tbl_professor_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_nota` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `qtde_atividade` SMALLINT(20) NOT NULL,
  `nome_atividade` VARCHAR(45) NOT NULL,
  `nota` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_frequencia` (
  `id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `presenca` INT ZEROFILL NOT NULL,
  `falta` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_aluno` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `RA` TINYINT(11) ZEROFILL NOT NULL,
  `nota_id` INT ZEROFILL UNSIGNED NOT NULL,
  `frequencia_id` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `frequencia_id`, `nota_id`),
  INDEX `fk_Aluno_tem_Nota_id` (`nota_id` ASC) VISIBLE,
  INDEX `fk_Aluno_tem_Frequencia_id` (`frequencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Nota`
    FOREIGN KEY (`nota_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_nota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Frequencia1`
    FOREIGN KEY (`frequencia_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_frequencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistemadeclasse`.`tbl_classe_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`tbl_classe_aluno` (
  `qtdade_aulas` INT NOT NULL,
  `qtdade_alunos` INT NOT NULL,
  `classe_id` INT UNSIGNED ZEROFILL NOT NULL,
  `aluno_id` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`classe_id`, `aluno_id`),
  INDEX `fk_Aluno_pertence_Classe_id` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_Classe_tem_Aluno_id` (`classe_id` ASC) INVISIBLE,
  CONSTRAINT `fk_Classe_has_Aluno_Classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classe_has_Aluno_Aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `db_sistemadeclasse`.`tbl_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `db_sistemadeclasse` ;

-- -----------------------------------------------------
-- Placeholder table for view `db_sistemadeclasse`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistemadeclasse`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `db_sistemadeclasse`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sistemadeclasse`.`view1`;
USE `db_sistemadeclasse`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
